from typing import Any, Dict, List, Optional, Tuple

class OutputSpec:
    force_field: Optional[str]
    parameterize_md: bool
    infer_bonds: bool
    add_hydrogens: bool
    compute_electrostatics: bool
    include_hetatm: bool
    remove_solvent: bool
    coord_format: "CoordFormat"
    models: Optional[List[int]]
    enable_caching: bool
    auto_terminal_caps: bool
    missing_residue_mode: "MissingResidueMode"
    compute_rbf: bool
    compute_vdw: bool
    rbf_num_neighbors: int

    def __init__(self, **kwargs) -> None: ...

class CoordFormat:
    Atom37: "CoordFormat"
    Atom14: "CoordFormat"
    Full: "CoordFormat"
    BackboneOnly: "CoordFormat"

class ErrorMode:
    Ignore: "ErrorMode"
    Warn: "ErrorMode"
    Fail: "ErrorMode"

class MissingResidueMode:
    SkipWarn: "MissingResidueMode"
    Fail: "MissingResidueMode"
    GaffFallback: "MissingResidueMode"
    ClosestMatch: "MissingResidueMode"

class AtomicSystem:
    # Minimal stub based on usage, refine as needed
    pass

def parse_pdb(path: str) -> Dict[str, Any]: ...
def parse_mmcif(path: str) -> Dict[str, Any]: ...
def parse_pqr(path: str) -> Dict[str, Any]: ...
def parse_structure(path: str, spec: Optional[OutputSpec] = None) -> Dict[str, Any]: ...
def load_forcefield(path: str) -> Dict[str, Any]: ...
def assign_gaff_atom_types(coordinates: Any, elements: List[str]) -> List[Optional[str]]: ...
def assign_masses(atom_names: List[str]) -> List[float]: ...
def assign_mbondi2_radii(atom_names: List[str], bonds: List[Tuple[int, int]]) -> List[float]: ...
def assign_obc2_scaling_factors(atom_names: List[str]) -> List[float]: ...
def get_water_model(name: str, rigid: bool) -> Dict[str, Any]: ...
def compute_bicubic_params(grid: List[List[float]]) -> List[List[List[float]]]: ...
def parameterize_molecule(coordinates: Any, elements: List[str], bond_tolerance: float = 1.3) -> Dict[str, Any]: ...
def parse_xtc(path: str) -> Dict[str, Any]: ...
def parse_dcd(path: str) -> Dict[str, Any]: ...
def parse_trr(path: str) -> Dict[str, Any]: ...
def parse_mdtraj_h5_metadata(path: str) -> Dict[str, Any]: ...
def parse_mdtraj_h5_frame(path: str, frame_idx: int) -> Dict[str, Any]: ...
def parse_mdcath_metadata(path: str) -> Dict[str, Any]: ...
def get_mdcath_replicas(path: str, domain_id: str, temperature: str) -> List[str]: ...
def parse_mdcath_frame(path: str, domain_id: str, temperature: str, replica: str, frame_idx: int) -> Dict[str, Any]: ...
