[package]
name = "proxide-io"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "IO and parsing modules for protein structures"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["protein", "pdb", "parser", "bioinformatics", "molecular-dynamics"]
categories = ["science", "parser-implementations"]

[package.metadata.docs.rs]
features = ["pdb", "cif", "xtc", "parallel", "foldcomp", "mmap"]

[lib]
crate-type = ["rlib"]

[dependencies]
proxide-core = { workspace = true }
proxide-geometry = { workspace = true }
log.workspace = true
thiserror.workspace = true
nom.workspace = true
quick-xml.workspace = true
flate2 = { workspace = true, optional = true }
memmap2 = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
lazy_static = { workspace = true }
molly = { workspace = true, optional = true }
hdf5 = { workspace = true, optional = true }
orx-parallel = { workspace = true, optional = true }
proxide-parallel-rt = { workspace = true, optional = true }

[features]
default = ["pdb", "cif", "xtc", "parallel"]
pdb = []
cif = []
ssbond = []
fetching = ["dep:reqwest"]
hdf5 = ["dep:hdf5"]
foldcomp = ["dep:flate2"]
xtc = ["dep:molly"]
parallel = ["dep:orx-parallel", "dep:proxide-parallel-rt"]
mmap = ["dep:memmap2"]
full = ["fetching", "hdf5", "foldcomp", "xtc", "parallel", "mmap", "pdb", "cif", "ssbond"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
httpmock = "0.7"
tempfile = "3.8"
hdf5 = { workspace = true }
