[package]
name = "proxide_py"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Python bindings for proxide_rs"
license.workspace = true

[lib]
name = "_proxider"
crate-type = ["cdylib"]

[dependencies]
proxide_rs = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"] }
numpy = { workspace = true }
nalgebra.workspace = true
pyo3-log = { workspace = true }
log = "0.4"

[features]
default = ["full"]
xtc = ["proxide_rs/xtc"]
mdcath = ["proxide_rs/mdcath"]
full = ["xtc", "mdcath", "proxide_rs/full"]
