[package]
name = "proxide-physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Physics and forcefield modules for protein structures"
license.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
proxide-core = { workspace = true }
proxide-geometry = { workspace = true }
proxide-gaff = { workspace = true }
quick-xml.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
proxide-core = { workspace = true, features = ["testing"] }
insta.workspace = true
approx.workspace = true

