[package]
name = "proxide-physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Physics and forcefield modules for protein structures"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["protein", "force-field", "physics", "molecular-dynamics", "bioinformatics"]
categories = ["science", "algorithms"]

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["rlib"]

[dependencies]
proxide-core = { workspace = true }
proxide-geometry = { workspace = true }
proxide-gaff = { workspace = true }
proxide-units = { workspace = true }
quick-xml.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
proxide-core = { workspace = true, features = ["testing"] }
insta.workspace = true
approx.workspace = true
bytemuck = "1.21.0"
