"""Static name -> relative-path index for fetchable/restricted force field assets.

Generated from the asset tree as it existed before amber/water/implicit/openmm_bundled
were converted from git-vendored to fetch-on-demand (see
.praxia/docs/specs/260824_license-provenance-verification.md). This lets
load_force_field("protein.ff14SB")-style bare-name lookups resolve to the right
relative path without needing the files present on disk (rglob can't find what isn't
vendored anymore) -- regenerate with scripts/generate_asset_index.py if the upstream
pinned commits in _fetch.py are ever bumped and the file catalog changes.
"""

ASSET_INDEX: dict[str, str] = {
  'DNA.OL15': 'amber/DNA.OL15.xml',
  'DNA.OL21': 'amber/DNA.OL21.xml',
  'DNA.bsc1': 'amber/DNA.bsc1.xml',
  'GLYCAM_06j-1': 'amber/GLYCAM_06j-1.xml',
  'RNA.OL3': 'amber/RNA.OL3.xml',
  'RNA.ROC': 'amber/RNA.ROC.xml',
  'amber03': 'openmm_bundled/amber03.xml',
  'amber03_obc': 'implicit/amber03_obc.xml',
  'amber10': 'openmm_bundled/amber10.xml',
  'amber10_obc': 'implicit/amber10_obc.xml',
  'amber14-all': 'openmm_bundled/amber14-all.xml',
  'amber19-all': 'openmm_bundled/amber19-all.xml',
  'amber96': 'openmm_bundled/amber96.xml',
  'amber96_obc': 'implicit/amber96_obc.xml',
  'amber99Test': 'openmm_bundled/amber99Test.xml',
  'amber99_obc': 'implicit/amber99_obc.xml',
  'amber99sb': 'openmm_bundled/amber99sb.xml',
  'amber99sbildn': 'openmm_bundled/amber99sbildn.xml',
  'amber99sbnmr': 'openmm_bundled/amber99sbnmr.xml',
  'amberfb15': 'openmm_bundled/amberfb15.xml',
  'amoeba2009': 'openmm_bundled/amoeba2009.xml',
  'amoeba2009_gk': 'openmm_bundled/amoeba2009_gk.xml',
  'amoeba2013': 'openmm_bundled/amoeba2013.xml',
  'amoeba2013_gk': 'openmm_bundled/amoeba2013_gk.xml',
  'amoeba2018': 'openmm_bundled/amoeba2018.xml',
  'amoeba2018_gk': 'openmm_bundled/amoeba2018_gk.xml',
  'charmm36': 'openmm_bundled/charmm36.xml',
  'charmm36_2024': 'openmm_bundled/charmm36_2024.xml',
  'charmm_polar_2013': 'openmm_bundled/charmm_polar_2013.xml',
  'charmm_polar_2019': 'openmm_bundled/charmm_polar_2019.xml',
  'charmm_polar_2023': 'openmm_bundled/charmm_polar_2023.xml',
  'ff14SB': 'amber/ff14SB.xml',
  'ff99': 'amber/ff99.xml',
  'ff99SB': 'amber/ff99SB.xml',
  'ff99SBildn': 'amber/ff99SBildn.xml',
  'gbn': 'openmm_bundled/implicit/gbn.xml',
  'gbn2': 'openmm_bundled/implicit/gbn2.xml',
  'glycam-hydrogens': 'openmm_bundled/glycam-hydrogens.xml',
  'hct': 'openmm_bundled/implicit/hct.xml',
  'hydrogens': 'openmm_bundled/hydrogens.xml',
  'iamoeba': 'openmm_bundled/iamoeba.xml',
  'lipid17': 'amber/lipid17.xml',
  'lipid17_merged': 'amber/lipid17_merged.xml',
  'lipid21': 'openmm_bundled/amber19/lipid21.xml',
  'lipid21_merged': 'amber/lipid21_merged.xml',
  'obc1': 'openmm_bundled/implicit/obc1.xml',
  'obc2': 'openmm_bundled/implicit/obc2.xml',
  'opc': 'openmm_bundled/amber14/opc.xml',
  'opc3': 'openmm_bundled/amber14/opc3.xml',
  'opc_standard': 'water/opc_standard.xml',
  'pdbNames': 'openmm_bundled/pdbNames.xml',
  'phosaa10': 'amber/phosaa10.xml',
  'protein.fb15': 'amber/protein.fb15.xml',
  'protein.ff03ua': 'amber/protein.ff03ua.xml',
  'protein.ff14SB': 'openmm_bundled/amber14/protein.ff14SB.xml',
  'protein.ff15ipq': 'amber/protein.ff15ipq.xml',
  'protein.ff19SB': 'amber/protein.ff19SB.xml',
  'protein.ff19ipq': 'openmm_bundled/amber19/protein.ff19ipq.xml',
  'residues': 'openmm_bundled/residues.xml',
  'spce': 'openmm_bundled/amber14/spce.xml',
  'swm4ndp': 'openmm_bundled/swm4ndp.xml',
  'tip3p': 'openmm_bundled/amber14/tip3p.xml',
  'tip3p-pme-b': 'openmm_bundled/charmm36/tip3p-pme-b.xml',
  'tip3p-pme-f': 'openmm_bundled/charmm36/tip3p-pme-f.xml',
  'tip3p_HFE_multivalent': 'water/tip3p_HFE_multivalent.xml',
  'tip3p_IOD_multivalent': 'water/tip3p_IOD_multivalent.xml',
  'tip3p_standard': 'water/tip3p_standard.xml',
  'tip3pfb': 'openmm_bundled/amber14/tip3pfb.xml',
  'tip4p2005': 'openmm_bundled/charmm36/tip4p2005.xml',
  'tip4pew': 'openmm_bundled/amber14/tip4pew.xml',
  'tip4pew_standard': 'water/tip4pew_standard.xml',
  'tip4pfb': 'openmm_bundled/amber14/tip4pfb.xml',
  'tip4pfb_standard': 'water/tip4pfb_standard.xml',
  'tip5p': 'openmm_bundled/charmm36/tip5p.xml',
  'tip5pew': 'openmm_bundled/charmm36/tip5pew.xml',
  'water': 'openmm_bundled/charmm36/water.xml',
}
