[package]
name = "proxide-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Foundational data structures for protein parsing"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["protein", "bioinformatics", "pdb", "molecular-dynamics", "structure"]
categories = ["science", "data-structures"]

[package.metadata.docs.rs]
features = ["serde"]

[lib]
crate-type = ["rlib"]

[dependencies]
# Linear algebra
nalgebra.workspace = true
bytemuck = "1.21.0"

# Parallelism (needed for some basic types if they implement parallel traits)
rayon.workspace = true
quick-xml.workspace = true

# Unit system types
proxide-units.workspace = true

# Serialization
serde = { version = "1.0", features = ["derive"], optional = true }

# Logging
log.workspace = true
thiserror.workspace = true

# Random
rand.workspace = true
rand_distr.workspace = true

[features]
default = []
serde = ["dep:serde"]
testing = []
