[package]
name = "proxide-geometry"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Geometric algorithms for protein structures"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["protein", "bioinformatics", "geometry", "molecular-dynamics", "structure"]
categories = ["science", "algorithms"]

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["rlib"]

[dependencies]
proxide-core = { workspace = true }
nalgebra.workspace = true
log.workspace = true
thiserror.workspace = true
bytemuck = "1.21.0"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "proxide-core/serde"]
