//! CCD (PDB Chemical Component Dictionary) id -> chem_comp.type lookup.
//!
//! Bundles a minimal subset of the official CCD (just id + chem_comp.type,
//! ~50k entries, ~80KiB compressed) so residue classification can recognize
//! genuinely CCD-registered non-canonical residues (MSE, D-amino acids, and
//! hundreds of others) regardless of a source file's raw ATOM/HETATM flag,
//! without needing the full ~116MB CCD (which also carries atom/bond geometry
//! this crate doesn't need -- it has its own heavy-atom templates for the
//! residues it builds atom37 representations for; see `chem::residues`).
//!
//! Generated by `scripts/generate_ccd_chem_comp_types.py` from
//! <https://files.wwpdb.org/pub/pdb/data/monomers/components.cif.gz> -- see
//! that script for regeneration instructions. Bundled at compile time via
//! `include_bytes!`, so no runtime network/file access is needed.
//!
//! Deliberately does NOT resolve CHARMM/AMBER protonation-variant naming
//! conventions like `HSD`/`CYM` -- those collide with unrelated (or
//! differently-modified) real CCD entries and are handled separately, with an
//! atom-composition safety check, by `chem::residues::resolve_variant_alias`.

use std::collections::HashMap;
use std::sync::OnceLock;

use prost::Message;

use crate::chem::pb::core_v1::ChemCompTypeTable;

const CCD_ASSET: &[u8] = include_bytes!("../../data/ccd_chem_comp_types.pb.zst");

/// Peptide-linking `_chem_comp.type` values, per the CCD schema (mirrors the
/// classification biotite/atomworks use for `filter_amino_acids`).
const PEPTIDE_LINKING_TYPES: &[&str] = &[
    "D-BETA-PEPTIDE, C-GAMMA LINKING",
    "D-GAMMA-PEPTIDE, C-DELTA LINKING",
    "D-PEPTIDE LINKING",
    "D-PEPTIDE NH3 AMINO TERMINUS",
    "D-PEPTIDE COOH CARBOXY TERMINUS",
    "L-BETA-PEPTIDE, C-GAMMA LINKING",
    "L-GAMMA-PEPTIDE, C-DELTA LINKING",
    "L-PEPTIDE LINKING",
    "L-PEPTIDE NH3 AMINO TERMINUS",
    "L-PEPTIDE COOH CARBOXY TERMINUS",
    "PEPTIDE LINKING",
];

fn table() -> &'static HashMap<String, String> {
    static TABLE: OnceLock<HashMap<String, String>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let decompressed = zstd::decode_all(CCD_ASSET).expect(
            "bundled CCD asset failed to decompress -- this is a build artifact bug, not a runtime data issue",
        );
        let parsed = ChemCompTypeTable::decode(decompressed.as_slice()).expect(
            "bundled CCD asset failed to decode as protobuf -- this is a build artifact bug, not a runtime data issue",
        );
        parsed
            .entries
            .into_iter()
            .map(|e| (e.id, e.chem_comp_type))
            .collect()
    })
}

/// Look up a residue name's `_chem_comp.type` in the bundled CCD subset.
/// Returns `None` if the name is not a registered CCD component at all.
pub fn chem_comp_type(res_name: &str) -> Option<&'static str> {
    table().get(res_name).map(String::as_str)
}

/// Whether a `_chem_comp.type` string (as returned by [`chem_comp_type`])
/// indicates a peptide-linking (amino-acid-like) component.
pub fn is_peptide_linking_type(chem_comp_type: &str) -> bool {
    PEPTIDE_LINKING_TYPES
        .iter()
        .any(|t| t.eq_ignore_ascii_case(chem_comp_type))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_standard_residues_are_peptide_linking() {
        for name in ["ALA", "HIS", "GLY", "CYS"] {
            let t =
                chem_comp_type(name).unwrap_or_else(|| panic!("{name} missing from bundled CCD"));
            assert!(
                is_peptide_linking_type(t),
                "{name} -> {t} should be peptide-linking"
            );
        }
    }

    #[test]
    fn test_mse_is_peptide_linking() {
        let t = chem_comp_type("MSE").expect("MSE missing from bundled CCD");
        assert!(is_peptide_linking_type(t));
    }

    #[test]
    fn test_charmm_amber_variant_collisions_are_not_reliably_peptide_linking() {
        // These are the exact collisions the alias table (chem::residues) is
        // designed to route around -- confirm the raw CCD data disagrees with
        // the CHARMM/AMBER interpretation, which is WHY the alias table (with
        // atom verification) exists rather than relying on CCD alone here.
        assert_eq!(chem_comp_type("HSD"), Some("NON-POLYMER"));
        assert_eq!(chem_comp_type("HID"), Some("NON-POLYMER"));
        // HSE/HIP/CYM are real CCD peptide-linking entries too, just for a
        // DIFFERENT molecule than the CHARMM/AMBER meaning -- still not
        // something a naive "resolve via CCD" step should be trusted to
        // disambiguate on its own.
        assert_eq!(chem_comp_type("HSE"), Some("L-PEPTIDE LINKING"));
        assert_eq!(chem_comp_type("HIP"), Some("L-PEPTIDE LINKING"));
        assert_eq!(chem_comp_type("CYM"), Some("L-PEPTIDE LINKING"));
    }

    #[test]
    fn test_unknown_name_returns_none() {
        assert_eq!(chem_comp_type("ZZZ_NOT_A_REAL_CODE"), None);
    }

    #[test]
    fn test_table_is_reasonably_comprehensive() {
        // Sanity floor -- the real CCD has 50k+ entries; a much smaller number
        // here would indicate a truncated/corrupted bundled asset.
        assert!(
            table().len() > 40_000,
            "only {} entries -- asset may be truncated",
            table().len()
        );
    }
}
