//! EspalomaCharge: Machine Learning-Enabled Ultrafast Partial Charge Assignment
//!
//! Port of EspalomaCharge to Rust with embedded weights.
//! Provides AM1-BCC quality partial charges orders of magnitude faster than traditional methods.
//!
//! ## Citation
//! Wang Y, Pulido I, Takaba K, Kaminow B, Scheen J, Wang L, Chodera JD.
//! "EspalomaCharge: Machine Learning-Enabled Ultrafast Partial Charge Assignment"
//! J. Phys. Chem. A 2024, 128, 20, 4160-4167. DOI: 10.1021/acs.jpca.4c01287
//! arXiv: https://arxiv.org/abs/2302.06758
//! GitHub: https://github.com/choderalab/espaloma_charge
//!
//! ## Architecture
//! - Espaloma v0.0.8 with SAGE graph neural network
//! - 4-layer message passing
//! - 128 hidden units per layer
//! - 116 feature dimensions

use bytemuck;
use nalgebra::{DMatrix, DVector};

/// Constants for the Espaloma v0.0.8 architecture
pub const FEATURE_UNITS: usize = 116;
pub const INPUT_UNITS: usize = 128;
pub const SAGE_HIDDEN: usize = 128;
pub const N_SAGE_LAYERS: usize = 4;

/// Embedded weights binary
#[repr(C, align(4))]
struct AlignedWeights<const N: usize>([u8; N]);

static WEIGHTS_BLOB: AlignedWeights<587284> =
    AlignedWeights(*include_bytes!("espaloma_v0_0_8.bin"));

pub static EMBEDDED_WEIGHTS: &[u8] = &WEIGHTS_BLOB.0;

/// Espaloma weight bundle
#[derive(Debug)]
pub struct EspalomaWeights {
    pub w_f_in: DMatrix<f32>,
    pub b_f_in: DVector<f32>,
    pub sages: Vec<SAGEWeights>,
    pub w_readout: DMatrix<f32>,
    pub b_readout: DVector<f32>,
}

#[derive(Debug)]
pub struct SAGEWeights {
    pub w_self: DMatrix<f32>,
    pub b_self: DVector<f32>,
    pub w_neigh: DMatrix<f32>,
}

impl EspalomaWeights {
    /// Load weights from a raw binary blob (generated by export_weights.py)
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() < 12 {
            return Err("Weight bundle too short".to_string());
        }

        // Simple manual check for safety (expect magic EXPA + version 1)
        if &bytes[0..4] != b"EXPA" {
            return Err("Invalid weight bundle magic".to_string());
        }

        if u32::from_le_bytes(bytes[4..8].try_into().unwrap()) != 1 {
            return Err("Unsupported weight bundle version".to_string());
        }

        let num_layers = u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize;
        if num_layers != N_SAGE_LAYERS {
            return Err(format!("Expected {} layers, found {}", N_SAGE_LAYERS, num_layers));
        }

        let data_len = bytes.len() - 12;
        let expected_len = (INPUT_UNITS * FEATURE_UNITS + INPUT_UNITS) * 4
            + N_SAGE_LAYERS * (SAGE_HIDDEN * SAGE_HIDDEN * 2 + SAGE_HIDDEN) * 4
            + (2 * SAGE_HIDDEN + 2) * 4;

        if data_len < expected_len {
            return Err(format!("Data length mismatch: expected {}, got {}", expected_len, data_len));
        }

        let data: &[f32] = bytemuck::cast_slice(&bytes[12..]);
        let mut pos = 0;

        // Projection
        let w_f_in = DM::from_row_slice(
            INPUT_UNITS,
            FEATURE_UNITS,
            &data[pos..pos + INPUT_UNITS * FEATURE_UNITS],
        );
        pos += INPUT_UNITS * FEATURE_UNITS;
        let b_f_in = DV::from_column_slice(&data[pos..pos + INPUT_UNITS]);
        pos += INPUT_UNITS;

        // SAGE Layers
        let mut sages = Vec::with_capacity(N_SAGE_LAYERS);
        for _ in 0..N_SAGE_LAYERS {
            let w_self = DM::from_row_slice(
                SAGE_HIDDEN,
                SAGE_HIDDEN,
                &data[pos..pos + SAGE_HIDDEN * SAGE_HIDDEN],
            );
            pos += SAGE_HIDDEN * SAGE_HIDDEN;
            let b_self = DV::from_column_slice(&data[pos..pos + SAGE_HIDDEN]);
            pos += SAGE_HIDDEN;
            let w_neigh = DM::from_row_slice(
                SAGE_HIDDEN,
                SAGE_HIDDEN,
                &data[pos..pos + SAGE_HIDDEN * SAGE_HIDDEN],
            );
            pos += SAGE_HIDDEN * SAGE_HIDDEN;
            sages.push(SAGEWeights {
                w_self,
                b_self,
                w_neigh,
            });
        }

        // Readout (2 output units: electronegativity and hardness)
        let w_readout = DM::from_row_slice(2, SAGE_HIDDEN, &data[pos..pos + 2 * SAGE_HIDDEN]);
        pos += 2 * SAGE_HIDDEN;
        let b_readout = DV::from_column_slice(&data[pos..pos + 2]);

        Ok(Self {
            w_f_in,
            b_f_in,
            sages,
            w_readout,
            b_readout,
        })
    }
}

type DM = DMatrix<f32>;
type DV = DVector<f32>;

/// Main inference entry point
pub fn infer_charges(
    weights: &EspalomaWeights,
    x: &DM, // (n_atoms, FEATURE_UNITS)
    senders: &[u32],
    receivers: &[u32],
    segment_ids: &[u32],
    num_graphs: usize,
    total_charges: &[f32], // per graph
) -> Vec<f32> {
    let n_atoms = x.nrows();

    // 1. Initial projection + Tanh
    // (n_atoms, 116) * (128, 116)^T + (128,)
    let mut h = (x * weights.w_f_in.transpose()).row_add_vec(&weights.b_f_in);
    h.apply(|v| *v = v.tanh());

    // 2. SAGE Layers
    for sage in &weights.sages {
        // Self loop contribution
        let h_self = (&h * sage.w_self.transpose()).row_add_vec(&sage.b_self);

        // Neighborhood aggregation (Mean)
        // DGL/Expaloma logic: agg = sum_m / deg
        let mut agg = DM::zeros(n_atoms, SAGE_HIDDEN);
        let mut deg = vec![0.0f32; n_atoms];

        for (&s, &r) in senders.iter().zip(receivers.iter()) {
            let s = s as usize;
            let r = r as usize;
            // Neighborhood transform after aggregation in DGL SAGEConv source (default)
            // msg = x[senders]
            // sum_m = scatter_add(msg, receivers)
            // agg = sum_m / deg
            // neigh_mean = agg @ w_neigh.T

            // Optimization: we can sum features then transform, or transform then sum.
            // Expaloma layers.py says: if in_feats > out_feats, transform before, else after.
            // Here in_feats(128) == out_feats(128), so "else" (after) applies.

            // Sum neighbor features into receiver
            let src_row = h.row(s);
            let mut dst_row = agg.row_mut(r);
            dst_row += src_row;
            deg[r] += 1.0;
        }

        // Normalize by degree
        for (i, deg_val) in deg.iter().enumerate().take(n_atoms) {
            if *deg_val > 0.0 {
                let mut row = agg.row_mut(i);
                row /= *deg_val;
            }
        }

        let h_neigh = agg * sage.w_neigh.transpose();

        h = h_self + h_neigh;
        h.apply(|v| *v = v.max(0.0)); // ReLU
    }

    // 3. Readout (E, S)
    let es = (h * weights.w_readout.transpose()).row_add_vec(&weights.b_readout);
    let e = es.column(0);
    let s = es.column(1);

    // 4. QEq (Charge Equilibrium)
    // q = -e * s_inv + s_inv * (tc_n + sum_e_s_inv_n) / sum_s_inv_n
    let s_inv: Vec<f32> = s.iter().map(|&val| 1.0 / val).collect();
    let e_s_inv: Vec<f32> = e
        .iter()
        .zip(s_inv.iter())
        .map(|(&ei, &si)| ei * si)
        .collect();

    let mut sum_s_inv = vec![0.0f32; num_graphs];
    let mut sum_e_s_inv = vec![0.0f32; num_graphs];

    for i in 0..n_atoms {
        let sid = segment_ids[i] as usize;
        sum_s_inv[sid] += s_inv[i];
        sum_e_s_inv[sid] += e_s_inv[i];
    }

    let mut charges = Vec::with_capacity(n_atoms);
    for i in 0..n_atoms {
        let sid = segment_ids[i] as usize;
        let si_inv = s_inv[i];
        let qi = -e[i] * si_inv + si_inv * (total_charges[sid] + sum_e_s_inv[sid]) / sum_s_inv[sid];
        charges.push(qi);
    }

    charges
}

/// Helper trait to add a vector to every row of a matrix
trait RowAddInplace {
    fn row_add_vec(&self, vec: &DVector<f32>) -> DMatrix<f32>;
}

impl RowAddInplace for DMatrix<f32> {
    fn row_add_vec(&self, vec: &DVector<f32>) -> DMatrix<f32> {
        let mut out = self.clone();
        for mut row in out.row_iter_mut() {
            row += vec.transpose();
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_weight_bundle_load_fail() {
        let bad_data = b"FAIL000000000000000000000000";
        let result = EspalomaWeights::from_bytes(bad_data);
        assert!(result.is_err());
    }

    #[test]
    fn test_weight_bundle_too_short() {
        let result = EspalomaWeights::from_bytes(&[0u8; 11]);
        assert_eq!(result.unwrap_err(), "Weight bundle too short");
    }

    #[test]
    fn test_weight_bundle_invalid_magic() {
        let result = EspalomaWeights::from_bytes(&[0u8; 12]);
        assert_eq!(result.unwrap_err(), "Invalid weight bundle magic");
    }

    #[test]
    fn test_embedded_weights_parsing() {
        let weights = EspalomaWeights::from_bytes(EMBEDDED_WEIGHTS).expect("Failed to parse embedded weights");
        assert_eq!(weights.sages.len(), 4);
        assert_eq!(weights.w_f_in.nrows(), 128);
        assert_eq!(weights.w_f_in.ncols(), 116);
    }

    #[test]
    fn test_infer_charges_simple() {
        let weights = EspalomaWeights::from_bytes(EMBEDDED_WEIGHTS).unwrap();
        
        // One atom (dummy features)
        let x = DM::zeros(1, FEATURE_UNITS);
        
        let senders = vec![];
        let receivers = vec![];
        let segment_ids = vec![0];
        let total_charges = vec![0.0];
        
        let charges = infer_charges(
            &weights,
            &x,
            &senders,
            &receivers,
            &segment_ids,
            1,
            &total_charges,
        );
        
        assert_eq!(charges.len(), 1);
        // Single atom with 0.0 total charge must have 0.0 charge due to QEq constraint
        assert!((charges[0]).abs() < 1e-5);
        
        // Two atoms, bonded
        let mut x2 = DM::zeros(2, FEATURE_UNITS);
        // Set some dummy features to differentiate them
        x2[(0, 0)] = 1.0; 
        x2[(1, 1)] = 1.0;
        
        let senders2 = vec![0, 1];
        let receivers2 = vec![1, 0];
        let segment_ids2 = vec![0, 0];
        let total_charges2 = vec![0.0];
        
        let charges2 = infer_charges(
            &weights,
            &x2,
            &senders2,
            &receivers2,
            &segment_ids2,
            1,
            &total_charges2,
        );
        
        assert_eq!(charges2.len(), 2);
        // Sum should be zero
        assert!((charges2[0] + charges2[1]).abs() < 1e-5);
    }

    #[test]
    fn test_weight_bundle_load_insufficient_data() {
        // Correct magic and version, but wrong size
        let mut data = vec![0u8; 12];
        data[0..4].copy_from_slice(b"EXPA");
        data[4..8].copy_from_slice(&1u32.to_le_bytes());
        data[8..12].copy_from_slice(&4u32.to_le_bytes());
        
        let result = EspalomaWeights::from_bytes(&data);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Data length mismatch"));
    }

    #[test]
    fn test_constants() {
        assert_eq!(FEATURE_UNITS, 116);
        assert_eq!(SAGE_HIDDEN, 128);
        assert_eq!(N_SAGE_LAYERS, 4);
    }
}
